### ISSUE TITLE
Infomation 컴포넌트 내부 Title 개선 요청

### ISSUE THREAD

**Issue by Bhanjo** [mju-likelion/inception#12]
Information.tsx에서 Title 컴포넌트가 있는데, 피그마상에선 Body1이 사용되고 있음 공통컴포넌트 Body 이용 필요

현재 공통컴포넌트 Body 미구현 상태 추후 개발 완료 후 다시 공지하겠습니다

body 텍스트 컴포넌트 제작완료했습니다~ 필요한 스타일링은 추가해서 쓰면 돼요

**Comment by yhyem** [comment]
타이포그래피가 글로벌 스타일로 다 추가되서 공통컴포넌트로 사용하지말고 그냥 글로벌스타일 속성으로 사용하는 게 더 낫지 않을까??
라는 생각인데 어떻게 생각하세요??
