### ISSUE TITLE
결과 페이지 일정 수정 버튼 클릭 시 라우팅 연결 요청

### ISSUE THREAD

**Issue by rninzi** [mju-likelion/inception#36]
결과 페이지의 일정 수정 버튼은 캘린더 컴포넌트 내부에 있어 컴포넌트 담당자이신 @Bhanjo 님과 얘기 나눈 결과, 직접 라우팅 연결해주시로 결정됐습니다.
아래는 일정 수정 기능과 관련한 Flow 이미지입니다.
<img width="786" alt="Screenshot 2023-07-20 at 1 29 21 PM" src="https://github.com/mju-likelion/inception/assets/90755664/a3b39d16-3e81-4148-a62d-53070aea3045">

**Comment by Bhanjo** [comment]
- [ ] 캘린더 수정 버튼 route 처리 route 위치는 update라는 새로운 페이지에서 관리하도록 결정
