### ISSUE TITLE
[Android] input 코드 자릿수 입력제한 미작동

### ISSUE THREAD

**Issue by Sujin-Hasse** [mju-likelion/inception#62]
![image](https://github.com/mju-likelion/inception/assets/81896174/a66c4983-3d9a-4d98-924b-584cc4006bf9)

**Comment by Sujin-Hasse** [comment]
<img width="1005" alt="image" src="https://github.com/mju-likelion/inception/assets/81896174/7869ce99-a5a2-4021-9123-42d93c4bdc62">
[ UX 개선 ] input 에서 enter 입력시 다음 플로우 진행

**Comment by Bhanjo** [comment]
이거 언제 해결되나요??

**Comment by Sujin-Hasse** [comment]
> 이거 언제 해결되나요??

웹, iOS 에서는 동작하는데 안드로이드에서는 작동이 안되어, 방법을 찾고 있어요...🥲 빨리.... 빨리 해보겠읍니다...
